// Auto-generated by zod-to-ts. Do not edit.
// This file is generated from src/lib/schemas/post.ts

export type CreatePost = {
    title: string;
    url?: (string | undefined) | null;
    textContent?: (string | undefined) | null;
    type: "LINK" | "TEXT";
};

export type Post = {
    id: string;
    title: string;
    url?: (string | undefined) | null;
    textContent?: (string | undefined) | null;
    points: number;
    author: {
        id: string;
        username: string;
    };
    createdAt: string | Date;
    commentCount: number;
    type: "LINK" | "TEXT";
    voteType?: (("UPVOTE" | "DOWNVOTE") | undefined) | null;
    hasVoted?: boolean | undefined;
    isBookmarked?: boolean | undefined;
};
