#!/bin/sh
# This line ensures that the script will exit immediately if a command exits with a non-zero status.
set -e

# Get changed files
# CHANGED_FILES=$(git diff --cached --name-only)

# # Check if any files in src/types/schemas have changed
# if echo "$CHANGED_FILES" | grep -q "^src/types/schemas/"; then
#   echo "📝 Generating types from schemas..."
#   yarn types:generate
# fi

# Run lint-staged for all staged files
# yarn lint-staged

